# Personal details
print("Nmae:Raj Narayan Singh ")
print("Age: 40")
print("Gender: male")
print("Marital status: Married")
print("Address: Urlabari-4,Moranng")
print("occupation: teacher")
print("Qualification: Master pf Science")
print("Interest: Science and technology")
print("contact no: 756674654")